# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: latest
  jobs:
    pre_build:
      - make -C docs generate
    post_install:
      - pip install ".[docs]"

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true
